spring:
  application:
    name: feign-app

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

greeting-other:
  ribbon:
    # the eureka vipAddress of the target service
    DeploymentContextBasedVipAddresses: web-flux-app