spring:
  cassandra:
    keyspace-name: tux_poc
    username: cassandra
    password: cassandra
    contact-points: atlin.local
    local-datacenter: datacenter1
cassandra:
  migration:
    keyspace-name: ${spring.cassandra.keyspace-name}
    script-locations: cassandra/migrator